// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors

import 'dart:convert';
import 'dart:typed_data';

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'dart:ffi' as ffi;

abstract class Native {
  Future<Platform> platform({dynamic hint});

  Future<bool> rustReleaseMode({dynamic hint});

  Future<void> playBeep(
      {required double freq,
      required int durationMs,
      required double amplification,
      dynamic hint});

  Future<void> playSong({required String sPath, dynamic hint});

  Future<void> initPlayer({dynamic hint});

  Future<void> play({dynamic hint});

  Future<void> pause({dynamic hint});

  Future<void> shuffle({dynamic hint});

  Future<void> setVolume({required double volume, dynamic hint});

  Future<void> setSpeed({required double speed, dynamic hint});

  Future<double> getVolume({dynamic hint});

  Future<void> getSpeed({dynamic hint});

  Future<void> load({required String source, dynamic hint});
}

enum Platform {
  Unknown,
  Android,
  Ios,
  Windows,
  Unix,
  MacIntel,
  MacApple,
  Wasm,
}

class NativeImpl extends FlutterRustBridgeBase<NativeWire> implements Native {
  factory NativeImpl(ffi.DynamicLibrary dylib) =>
      NativeImpl.raw(NativeWire(dylib));

  NativeImpl.raw(NativeWire inner) : super(inner);

  Future<Platform> platform({dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_platform(port_),
        parseSuccessData: _wire2api_platform,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "platform",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<bool> rustReleaseMode({dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_rust_release_mode(port_),
        parseSuccessData: _wire2api_bool,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "rust_release_mode",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> playBeep(
          {required double freq,
          required int durationMs,
          required double amplification,
          dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_play_beep(port_, _api2wire_f32(freq),
            _api2wire_u64(durationMs), _api2wire_f32(amplification)),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "play_beep",
          argNames: ["freq", "durationMs", "amplification"],
        ),
        argValues: [freq, durationMs, amplification],
        hint: hint,
      ));

  Future<void> playSong({required String sPath, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) =>
            inner.wire_play_song(port_, _api2wire_String(sPath)),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "play_song",
          argNames: ["sPath"],
        ),
        argValues: [sPath],
        hint: hint,
      ));

  Future<void> initPlayer({dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_init_player(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "init_player",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> play({dynamic hint}) => executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_play(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "play",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> pause({dynamic hint}) => executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_pause(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "pause",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> shuffle({dynamic hint}) => executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_shuffle(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "shuffle",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> setVolume({required double volume, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_set_volume(port_, _api2wire_f32(volume)),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "set_volume",
          argNames: ["volume"],
        ),
        argValues: [volume],
        hint: hint,
      ));

  Future<void> setSpeed({required double speed, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_set_speed(port_, _api2wire_f32(speed)),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "set_speed",
          argNames: ["speed"],
        ),
        argValues: [speed],
        hint: hint,
      ));

  Future<double> getVolume({dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_get_volume(port_),
        parseSuccessData: _wire2api_f32,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "get_volume",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> getSpeed({dynamic hint}) => executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_get_speed(port_),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "get_speed",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  Future<void> load({required String source, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_load(port_, _api2wire_String(source)),
        parseSuccessData: _wire2api_unit,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "load",
          argNames: ["source"],
        ),
        argValues: [source],
        hint: hint,
      ));

  // Section: api2wire
  ffi.Pointer<wire_uint_8_list> _api2wire_String(String raw) {
    return _api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  double _api2wire_f32(double raw) {
    return raw;
  }

  int _api2wire_u64(int raw) {
    return raw;
  }

  int _api2wire_u8(int raw) {
    return raw;
  }

  ffi.Pointer<wire_uint_8_list> _api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  // Section: api_fill_to_wire

}

// Section: wire2api
bool _wire2api_bool(dynamic raw) {
  return raw as bool;
}

double _wire2api_f32(dynamic raw) {
  return raw as double;
}

Platform _wire2api_platform(dynamic raw) {
  return Platform.values[raw];
}

void _wire2api_unit(dynamic raw) {
  return;
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void wire_platform(
    int port_,
  ) {
    return _wire_platform(
      port_,
    );
  }

  late final _wire_platformPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_platform');
  late final _wire_platform =
      _wire_platformPtr.asFunction<void Function(int)>();

  void wire_rust_release_mode(
    int port_,
  ) {
    return _wire_rust_release_mode(
      port_,
    );
  }

  late final _wire_rust_release_modePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_rust_release_mode');
  late final _wire_rust_release_mode =
      _wire_rust_release_modePtr.asFunction<void Function(int)>();

  void wire_play_beep(
    int port_,
    double freq,
    int duration_ms,
    double amplification,
  ) {
    return _wire_play_beep(
      port_,
      freq,
      duration_ms,
      amplification,
    );
  }

  late final _wire_play_beepPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Float, ffi.Uint64, ffi.Float)>>('wire_play_beep');
  late final _wire_play_beep =
      _wire_play_beepPtr.asFunction<void Function(int, double, int, double)>();

  void wire_play_song(
    int port_,
    ffi.Pointer<wire_uint_8_list> s_path,
  ) {
    return _wire_play_song(
      port_,
      s_path,
    );
  }

  late final _wire_play_songPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_play_song');
  late final _wire_play_song = _wire_play_songPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_init_player(
    int port_,
  ) {
    return _wire_init_player(
      port_,
    );
  }

  late final _wire_init_playerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_init_player');
  late final _wire_init_player =
      _wire_init_playerPtr.asFunction<void Function(int)>();

  void wire_play(
    int port_,
  ) {
    return _wire_play(
      port_,
    );
  }

  late final _wire_playPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_play');
  late final _wire_play = _wire_playPtr.asFunction<void Function(int)>();

  void wire_pause(
    int port_,
  ) {
    return _wire_pause(
      port_,
    );
  }

  late final _wire_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_pause');
  late final _wire_pause = _wire_pausePtr.asFunction<void Function(int)>();

  void wire_shuffle(
    int port_,
  ) {
    return _wire_shuffle(
      port_,
    );
  }

  late final _wire_shufflePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_shuffle');
  late final _wire_shuffle = _wire_shufflePtr.asFunction<void Function(int)>();

  void wire_set_volume(
    int port_,
    double volume,
  ) {
    return _wire_set_volume(
      port_,
      volume,
    );
  }

  late final _wire_set_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'wire_set_volume');
  late final _wire_set_volume =
      _wire_set_volumePtr.asFunction<void Function(int, double)>();

  void wire_set_speed(
    int port_,
    double speed,
  ) {
    return _wire_set_speed(
      port_,
      speed,
    );
  }

  late final _wire_set_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'wire_set_speed');
  late final _wire_set_speed =
      _wire_set_speedPtr.asFunction<void Function(int, double)>();

  void wire_get_volume(
    int port_,
  ) {
    return _wire_get_volume(
      port_,
    );
  }

  late final _wire_get_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_volume');
  late final _wire_get_volume =
      _wire_get_volumePtr.asFunction<void Function(int)>();

  void wire_get_speed(
    int port_,
  ) {
    return _wire_get_speed(
      port_,
    );
  }

  late final _wire_get_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_speed');
  late final _wire_get_speed =
      _wire_get_speedPtr.asFunction<void Function(int)>();

  void wire_load(
    int port_,
    ffi.Pointer<wire_uint_8_list> source,
  ) {
    return _wire_load(
      port_,
      source,
    );
  }

  late final _wire_loadPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_load');
  late final _wire_load = _wire_loadPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list(
    int len,
  ) {
    return _new_uint_8_list(
      len,
    );
  }

  late final _new_uint_8_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list');
  late final _new_uint_8_list = _new_uint_8_listPtr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint8 Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
